Added options remaining issuance to spreadsheet
captable/ocx pull request #39
Opened 2023-05-03 22:03 UTC by daviidy

# ASK
Issue #18

2023-05-04 13:27 UTC, pjohnmeyer requested changes

2023-05-04 13:27 UTC, pjohnmeyer commented on src/workbook/stakeholder-sheet/holdings-columns.ts
> +      .addBlankCell(Styles.default)
**Non-blocking:** If you put the `{style: Styles.default}` as a parameter to the nested range, you shouldn't need to pass it on LL41-43

2023-05-04 13:27 UTC, pjohnmeyer commented on src/workbook/stakeholder-sheet/holdings-columns.ts
> +      .addBlankCell(Styles.default)
**Non-blocking:** Use `.addBlankCells` instead of multiple `.addBlankCell` calls.

2023-05-04 17:15 UTC, daviidy commented on src/workbook/stakeholder-sheet/holdings-columns.ts
> +
One of the criteria we can look at is whether or not we need to consume objects from the package in order to do the calculations. If we need to consume objects we can go with the model.
But as shown in issue #19, we can rely on the values in the spreadsheet.

2023-05-05 12:46 UTC, pjohnmeyer commented on src/workbook/stakeholder-sheet/holdings-columns.ts
> +
Yes, in the case of #19 there are no "in-tool" calculations -- other than assembling the formula. That definitely belongs in the workbook code b/c only the workbook knows where the cells are.

We can discuss the other cases next week when I'm not on-call; I'm planning on spending part of my Tuesday documenting some things in OCX.

2023-05-05 17:00 UTC, pjohnmeyer approved these changes

2023-05-05 17:00 UTC, merged